### PR TITLE
fixed missing VPX_ Prefixes in webpimg.c

### PR DESCRIPTION
**Pull request by konqui**
can you please merge this into your patch repo.

so  i can update the patch url in the gd FORMULA to the one of your repository and can remove my temp repository which is included now

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Will do. Has this patch been submitted upstream? Can you link me to the relevant PR? Thanks!

**Comment by konqui** [comment]
Yes the pull request for the patch is here https://github.com/Homebrew/patches/pull/7

**Comment by konqui** [comment]
i got an answer from the original bitbucket project maintainer. they moved to github.

so maybe it would be the better way to switch to there new repo and stop using their old bitbucket links in the formula.

--------------------------------------------------------------------------------------
Pierre Joye kommentierte Pull Request #28:
fixed a few typos/missing VPX_ prefixes in webpimg.c
hi,
Thanks for the PR!
We moved to http://github.com/libgd, if only we could close that one and make it read only :)
--------------------------------------------------------------------------------------

**Comment by mikemcquaid** [comment]
@konqui Yeh, that seems like a good idea. Feel free to add that to your PR :+1:

**Comment by konqui** [comment]
now i have added the libgd archive located on github in favor to the old one on bitbucket.

it should be ready to merge

**Pull request closed without merging**
