### PR TITLE
thrift090: Moving patches from gist archive

### PR DESCRIPTION
**Pull request by rafaelverger**
Moving patches from my own gist repository (https://gist.github.com/rafaelverger/2602feff4050df0693c5/) to here.

### CODE REVIEW

**Comment by rafaelverger** [comment]
@DomT4 @mikemcquaid can you check this, please?

**Comment by DomT4** [comment]
Will get to this in the morning, but Mike can beat me to it if he wants to.

**Comment by mikemcquaid** [comment]
@rafaelverger Can you link to the relevant formula? Thanks!

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew-versions/pull/961 & https://github.com/rafaelverger/homebrew-versions/blob/master/thrift090.rb

It's a Versions one.

**Pull request merged**
